name: SDEV Final Project

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-tk xvfb

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        # If you have other dependencies, install them here
        # pip install -r requirements.txt

    - name: Run GUI application
      run: |
        xvfb-run --auto-servernum --server-args='-screen 0 1024x768x24' python GUI.py

    - name: Run inventory management
      run: |
        xvfb-run --auto-servernum --server-args='-screen 0 1024x768x24' python inventory2.py


